/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirlines;

import Business.Airline;
import Business.Airplane;
import Business.PlaneDetails;
import com.sun.tools.javac.util.StringUtils;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */

public class ViewScheduledPlanesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewScheduledFightJPanel
     */
    private PlaneDetails planeDetails;
    private JPanel userProcessContainer;
    private Airplane airplane;
    
    public ViewScheduledPlanesJPanel(PlaneDetails planeDetails, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.planeDetails = planeDetails;
        populateFields();
    }
    
    private void populateFields(){
        flightIdTextField.setText(planeDetails.getFlightId()+"");
        jXDatePicker1.setDate(planeDetails.getDepatureDate());
        hourComboBox.removeAllItems();
        minComboBox.removeAllItems();
        for (int i = 0; i < 24; i++) {
            hourComboBox.addItem(i);
        }

        for (int j = 0; j < 60; j++) {
            minComboBox.addItem(j);

        }
        startingPointTextField.setText(planeDetails.getDepaturePort()+"");
        destinationTextField.setText(planeDetails.getDestinationPort()+"");
        pricePerSeatTextField.setText(planeDetails.getPriceOfSeat()+"");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startingPointTextField = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        minComboBox = new javax.swing.JComboBox();
        hourComboBox = new javax.swing.JComboBox();
        saveViewScheduledFLightButton = new javax.swing.JButton();
        updateViewScheduledFLightButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButtonViewAllPlanes = new javax.swing.JButton();

        setBackground(new java.awt.Color(55, 96, 128));

        pricePerSeatTextField.setEnabled(false);
        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Price per Seat");

        destinationTextField.setEnabled(false);

        jLabel6.setText("Destination");

        jLabel4.setText("Time ");

        jLabel3.setText("Date ");

        flightIdTextField.setEnabled(false);

        jLabel2.setText("Flight Id");

        jLabel5.setText("Starting Point");

        startingPointTextField.setEnabled(false);

        jXDatePicker1.setEnabled(false);

        minComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        minComboBox.setEnabled(false);

        hourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hourComboBox.setEnabled(false);

        saveViewScheduledFLightButton.setText("Save");
        saveViewScheduledFLightButton.setEnabled(false);
        saveViewScheduledFLightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveViewScheduledFLightButtonActionPerformed(evt);
            }
        });

        updateViewScheduledFLightButton.setText("Update");
        updateViewScheduledFLightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateViewScheduledFLightButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 204, 67));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Scheduled Plane");

        backButtonViewAllPlanes.setBackground(new java.awt.Color(171, 204, 67));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateViewScheduledFLightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveViewScheduledFLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinationTextField)
                            .addComponent(startingPointTextField)
                            .addComponent(pricePerSeatTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flightIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButtonViewAllPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButtonViewAllPlanes))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startingPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateViewScheduledFLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(saveViewScheduledFLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricePerSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(329, 329, 329))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void updateViewScheduledFLightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateViewScheduledFLightButtonActionPerformed
        // TODO add your handling code here:
        updateViewScheduledFLightButton.setEnabled(false);
        saveViewScheduledFLightButton.setEnabled(true);
        pricePerSeatTextField.setEnabled(true);
        startingPointTextField.setEnabled(true);
        destinationTextField.setEnabled(true);
        jXDatePicker1.setEnabled(true);
        hourComboBox.setEnabled(true);
        minComboBox.setEnabled(true);        
    }//GEN-LAST:event_updateViewScheduledFLightButtonActionPerformed

    private void saveViewScheduledFLightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveViewScheduledFLightButtonActionPerformed
        // TODO add your handling code here:
        
        planeDetails.setDestinationPort(destinationTextField.getText());
        planeDetails.setDepaturePort(startingPointTextField.getText());
        planeDetails.setDepatureTime(hourComboBox.getSelectedItem().toString() + ":" + minComboBox.getSelectedItem().toString());
        planeDetails.setDestinationPort(destinationTextField.getText());
        planeDetails.setDepatureDate(jXDatePicker1.getDate());
        planeDetails.setPriceOfSeat(Double.parseDouble(pricePerSeatTextField.getText()));
        
        JOptionPane.showMessageDialog(null,"Plane details updated successfully!");
        saveViewScheduledFLightButton.setEnabled(false);
        updateViewScheduledFLightButton.setEnabled(true);
        pricePerSeatTextField.setEnabled(false);
        startingPointTextField.setEnabled(false);
        destinationTextField.setEnabled(false);
        jXDatePicker1.setEnabled(false);
        hourComboBox.setEnabled(false);
        minComboBox.setEnabled(false);       
        
    }//GEN-LAST:event_saveViewScheduledFLightButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);         
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewAllPlanesPanel viewAllFlightsPanel  = (ViewAllPlanesPanel) component;
        viewAllFlightsPanel.populateAiplaneTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JComboBox hourComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JComboBox minComboBox;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JButton saveViewScheduledFLightButton;
    private javax.swing.JTextField startingPointTextField;
    private javax.swing.JButton updateViewScheduledFLightButton;
    // End of variables declaration//GEN-END:variables
}
