/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.BookFlight;

import Business.Airline;
import Business.AirplaneFleet;
import Business.FleetSchedule;
import Business.Person;
import Business.PlaneDetails;
import Business.Seat;
import Business.TravelAgency;
import Interface.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Adwait
 */
public class ConfirmBooking extends javax.swing.JPanel {
    
    private TravelAgency travelAgency ;
    private JPanel userProcessContainer;
    private PlaneDetails planeDetails ;
    private  Seat seatBooked ;
    private String multiSeat;
  
     public ConfirmBooking(TravelAgency travelAgency , JPanel userProcessContainer,PlaneDetails planeDetails , Seat seatBooked ,String multiSeat ) {
        initComponents();
          this.userProcessContainer = userProcessContainer ;
          this.travelAgency = travelAgency ;
          this.planeDetails = planeDetails ;
          this.seatBooked =seatBooked ;
          this.multiSeat = multiSeat;
          intitialTextField();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        depaturePortTextField = new javax.swing.JTextField();
        timeTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airlineTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SeatNumberTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        custIDTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(55, 96, 128));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(925, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 204, 67));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YOUR BOOKING DETAILS ARE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 9, 841, -1));

        backButton.setBackground(new java.awt.Color(171, 204, 67));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 18, -1, -1));

        jLabel4.setText("Time");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 20));

        airplaneIdTextField.setEnabled(false);
        add(airplaneIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 135, 85, -1));

        depaturePortTextField.setEnabled(false);
        add(depaturePortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 100, -1));

        timeTextField.setEnabled(false);
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 100, -1));

        dateTextField.setEnabled(false);
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 310, -1));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 40, -1));

        jLabel5.setText("Starting Point");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, -1));

        flightIdTextField.setEnabled(false);
        add(flightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 97, 100, -1));

        jLabel11.setText("Airplane Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 138, -1, -1));

        jLabel2.setText("Flight Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 94, 130, 30));

        airlineTextField.setEnabled(false);
        add(airlineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 97, 85, -1));

        jLabel10.setText("Airline");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 100, -1, -1));

        pricePerSeatTextField.setEnabled(false);
        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });
        add(pricePerSeatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 100, -1));

        jLabel7.setText("Price per Seat");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 110, -1));

        destinationPortTextField.setEnabled(false);
        add(destinationPortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, -1));

        jLabel6.setText("Destination");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, -1));

        jLabel14.setText("Seat Number");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 80, 20));

        SeatNumberTextField.setEnabled(false);
        SeatNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumberTextFieldActionPerformed(evt);
            }
        });
        add(SeatNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 85, -1));

        jLabel15.setText("Customer Name");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 20));

        custNameTextField.setEnabled(false);
        custNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTextFieldActionPerformed(evt);
            }
        });
        add(custNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 85, -1));

        jLabel16.setText("Customer ID");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        custIDTextField.setEnabled(false);
        custIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTextFieldActionPerformed(evt);
            }
        });
        add(custIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 85, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void intitialTextField() {
        flightIdTextField.setText(String.valueOf(planeDetails.getFlightId()));
        dateTextField.setText(planeDetails.getDepatureDate()+"");
        timeTextField.setText(planeDetails.getDepatureTime());
        depaturePortTextField.setText(planeDetails.getDepaturePort());
        destinationPortTextField.setText(planeDetails.getDestinationPort());
        pricePerSeatTextField.setText(String.valueOf(planeDetails.getPriceOfSeat()));
        airlineTextField.setText(planeDetails.getAirplane().getAirline());
        airplaneIdTextField.setText(String.valueOf(planeDetails.getAirplane().getAirplaneId()));
        SeatNumberTextField.setText(multiSeat);
        custIDTextField.setText(seatBooked.getPerson().getPersonId()+ "");
        custNameTextField.setText(seatBooked.getPerson().getName());
        
        
        
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout =  (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void SeatNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumberTextFieldActionPerformed

    private void custNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTextFieldActionPerformed

    private void custIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SeatNumberTextField;
    private javax.swing.JTextField airlineTextField;
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField custIDTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField depaturePortTextField;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
